<?php

namespace Gymers\TonglianPay\Utils;

/**
 * 附录
*/
class AppendixUtil
{
    /**
     * 银行编码
     * 
     * 银行编码使用建议按照明确银行编码优先于分类银行编码优先于统一银行编码，存在明确银行编码时，建议使用明确银行编码，对中小型农商行优先使用分类银行，除以上情况可使用统一银行编码。
    */
    public const BANK_CODE = [
        ['bank_code' => '01000000', 'bank_name' => '邮储银行'],
        ['bank_code' => '01020000', 'bank_name' => '工商银行'],
        ['bank_code' => '01030000', 'bank_name' => '农业银行'],
        ['bank_code' => '01040000', 'bank_name' => '中国银行'],
        ['bank_code' => '01050000', 'bank_name' => '建设银行'],
        ['bank_code' => '03010000', 'bank_name' => '交通银行'],
        ['bank_code' => '03020000', 'bank_name' => '中信银行'],
        ['bank_code' => '03030000', 'bank_name' => '光大银行'],
        ['bank_code' => '03040000', 'bank_name' => '华夏银行'],
        ['bank_code' => '03050000', 'bank_name' => '民生银行'],
        ['bank_code' => '03060000', 'bank_name' => '广发银行'],
        ['bank_code' => '03080000', 'bank_name' => '招商银行'],
        ['bank_code' => '03090000', 'bank_name' => '兴业银行'],
        ['bank_code' => '03100000', 'bank_name' => '浦发银行'],
        ['bank_code' => '04012900', 'bank_name' => '上海银行'],
        ['bank_code' => '04031000', 'bank_name' => '北京银行'],
        ['bank_code' => '04105840', 'bank_name' => '平安银行'],
        ['bank_code' => '00001014', 'bank_name' => '农村商业银行'],
        ['bank_code' => '00001015', 'bank_name' => '农村合作银行'],
        ['bank_code' => '00001016', 'bank_name' => '村镇银行'],
        ['bank_code' => '00001017', 'bank_name' => '民营银行'],
        ['bank_code' => '00001018', 'bank_name' => '城市信用社'],
        ['bank_code' => '00001019', 'bank_name' => '农村信用社'],
        ['bank_code' => '11111111', 'bank_name' => '统一银行'],
    ];

    /**
     * 证件类型
     * 
    */
    public const ID_TYPE = [
        ['id_type' => '00', 'id_name' => '暂住证'],
        ['id_type' => '01', 'id_name' => '身份证'],
        ['id_type' => '02', 'id_name' => '户口本'],
        ['id_type' => '03', 'id_name' => '军官证'],
        ['id_type' => '04', 'id_name' => '警官证'],
        ['id_type' => '05', 'id_name' => '士兵证'],
        ['id_type' => '06', 'id_name' => '文职干部证'],
        ['id_type' => '07', 'id_name' => '护照'],
        ['id_type' => '08', 'id_name' => '台胞证（港澳台同胞回乡证）'],
        ['id_type' => '09', 'id_name' => '外国人永久居住证'],
        ['id_type' => '10', 'id_name' => '外国护照'],
        ['id_type' => '11', 'id_name' => '港澳居民来往内地通行证'],
        ['id_type' => '12', 'id_name' => '台湾居民来往大陆通行证'],
        ['id_type' => '13', 'id_name' => '营业执照'],
        ['id_type' => '14', 'id_name' => '统一社会信用'],
        ['id_type' => '15', 'id_name' => '登记证书'],
        ['id_type' => '16', 'id_name' => '批文'],
        ['id_type' => '17', 'id_name' => '其他证件'],
        ['id_type' => '18', 'id_name' => '临时身份证'],
    ];

    /**
     * 所属行业
    */
    public const INDUSTRY = [
        ['mccid' => '5978', 'mcc_name' => '打字机商店—销售、服务和出租'],
        ['mccid' => '5983', 'mcc_name' => '燃料经销商－燃油、木材、煤炭和液化石油'],
        ['mccid' => '5995', 'mcc_name' => '宠物商店、宠物食品及用品'],
        ['mccid' => '5996', 'mcc_name' => '游泳池－销售、供应和服务'],
        ['mccid' => '5997', 'mcc_name' => '电动剃须刀商店－销售和服务'],
        ['mccid' => '5999', 'mcc_name' => '其他专门零售店'],
        ['mccid' => '6513', 'mcc_name' => '不动产管理－物业管理'],
        ['mccid' => '7210', 'mcc_name' => '洗衣店'],
        ['mccid' => '7211', 'mcc_name' => '洗熨服务（自助洗衣服务）'],
        ['mccid' => '7216', 'mcc_name' => '干洗店'],
        ['mccid' => '7251', 'mcc_name' => '修鞋店、擦鞋店、帽子清洗店'],
        ['mccid' => '7276', 'mcc_name' => '税收准备服务'],
        ['mccid' => '7278', 'mcc_name' => '购物服务及会所（贸易、经纪服务）'],
        ['mccid' => '7338', 'mcc_name' => '复印及绘图服务'],
        ['mccid' => '7342', 'mcc_name' => '灭虫及消毒服务'],
        ['mccid' => '7361', 'mcc_name' => '职业中介、临时工'],
        ['mccid' => '7375', 'mcc_name' => '信息检索服务'],
        ['mccid' => '7379', 'mcc_name' => '未列入其他代码的计算机维护和修理服务'],
        ['mccid' => '7393', 'mcc_name' => '侦探、保安、安全服务'],
        ['mccid' => '7395', 'mcc_name' => '照相洗印服务'],
        ['mccid' => '7531', 'mcc_name' => '车体维修店'],
        ['mccid' => '7534', 'mcc_name' => '轮胎翻新、维修店'],
        ['mccid' => '7535', 'mcc_name' => '汽车喷漆店'],
        ['mccid' => '7993', 'mcc_name' => '电子游戏供给'],
        ['mccid' => '8049', 'mcc_name' => '手足病医生'],
        ['mccid' => '8244', 'mcc_name' => '商业和文秘学校（中等专业学校）'],
        ['mccid' => '8249', 'mcc_name' => '贸易和职业学校（职业技能培训）'],
        ['mccid' => '8641', 'mcc_name' => '市民、社会及友爱组织'],
        ['mccid' => '8661', 'mcc_name' => '宗教组织'],
        ['mccid' => '4722', 'mcc_name' => '旅行社'],
        ['mccid' => '4733', 'mcc_name' => '大型景区门票'],
        ['mccid' => '5013', 'mcc_name' => '机动车供应及零配件（批发商）'],
        ['mccid' => '5021', 'mcc_name' => '办公及商务家具（批发商）'],
        ['mccid' => '5039', 'mcc_name' => '未列入其他代码的建材批发（批发商）'],
        ['mccid' => '5044', 'mcc_name' => '办公、影印及微缩摄影器材（批发商）'],
        ['mccid' => '5045', 'mcc_name' => '计算机、计算机外围设备（批发商）'],
        ['mccid' => '5046', 'mcc_name' => '未列入其他代码的商用器材（批发商）'],
        ['mccid' => '5047', 'mcc_name' => '牙科/实验室/医疗/眼科医院器材和用品（批发商）'],
        ['mccid' => '5051', 'mcc_name' => '金属产品服务商和公司（批发商）'],
        ['mccid' => '5065', 'mcc_name' => '电器零件和设备（批发商）'],
        ['mccid' => '5072', 'mcc_name' => '五金器材及用品（批发商）'],
        ['mccid' => '5074', 'mcc_name' => '管道和供暖设备（批发商）'],
        ['mccid' => '5111', 'mcc_name' => '文具、办公用品、复印纸和书写纸（批发商）'],
        ['mccid' => '5122', 'mcc_name' => '药品、药品经营者（批发商）'],
        ['mccid' => '5131', 'mcc_name' => '布料、缝纫用品和其他纺织品（批发商）'],
        ['mccid' => '5137', 'mcc_name' => '男女及儿童制服和服装（批发商）'],
        ['mccid' => '5139', 'mcc_name' => '鞋类（批发商）'],
        ['mccid' => '5172', 'mcc_name' => '石油及石油产品（批发商）'],
        ['mccid' => '5192', 'mcc_name' => '书、期刊和报纸（批发商）'],
        ['mccid' => '5193', 'mcc_name' => '花木栽种用品、苗木和花卉（批发商）'],
        ['mccid' => '5198', 'mcc_name' => '油漆、清漆用品（批发商）'],
        ['mccid' => '5998', 'mcc_name' => '其他批发商'],
        ['mccid' => '5398', 'mcc_name' => '大型企业批发'],
        ['mccid' => '4458', 'mcc_name' => '烟草配送'],
        ['mccid' => '8062', 'mcc_name' => '公立、医保医院'],
        ['mccid' => '8211', 'mcc_name' => '中小学校（公立）'],
        ['mccid' => '8220', 'mcc_name' => '普通高校（公立）'],
        ['mccid' => '8398', 'mcc_name' => '慈善和社会公益服务组织'],
        ['mccid' => '7012', 'mcc_name' => '分时使用的别墅或度假用房'],
        ['mccid' => '5811', 'mcc_name' => '包办伙食，宴会承包商'],
        ['mccid' => '5812', 'mcc_name' => '就餐场所和餐馆，营业面积＞100 平方米'],
        ['mccid' => '5813', 'mcc_name' => '饮酒场所（酒吧、酒馆、夜总会、鸡尾酒大厅、迪斯科舞厅）'],
        ['mccid' => '5094', 'mcc_name' => '贵重珠宝、首饰，钟表零售'],
        ['mccid' => '5937', 'mcc_name' => '古玩复制店'],
        ['mccid' => '5950', 'mcc_name' => '玻璃器皿和水晶饰品店'],
        ['mccid' => '5970', 'mcc_name' => '工艺美术商店'],
        ['mccid' => '5971', 'mcc_name' => '艺术商和画廊'],
        ['mccid' => '7297', 'mcc_name' => '按摩店'],
        ['mccid' => '7298', 'mcc_name' => '保健及美容 SPA'],
        ['mccid' => '7829', 'mcc_name' => '电影和录像创作、发行'],
        ['mccid' => '7911', 'mcc_name' => '歌舞厅'],
        ['mccid' => '7922', 'mcc_name' => '戏剧制片（不含电影）、演出和票务'],
        ['mccid' => '7929', 'mcc_name' => '未列入其他代码的乐队、文艺表演'],
        ['mccid' => '7932', 'mcc_name' => '台球、撞球场所'],
        ['mccid' => '7933', 'mcc_name' => '保龄球馆'],
        ['mccid' => '7941', 'mcc_name' => '商业体育场馆、职业体育俱乐部、运动场和体育推广公司'],
        ['mccid' => '7992', 'mcc_name' => '公共高尔夫球场'],
        ['mccid' => '7994', 'mcc_name' => '大型游戏机和游戏场所'],
        ['mccid' => '7996', 'mcc_name' => '游乐园、马戏团、嘉年华、占卜'],
        ['mccid' => '7997', 'mcc_name' => '会员俱乐部、乡村俱乐部以及私人高尔夫课程班'],
        ['mccid' => '7998', 'mcc_name' => '水族馆、海洋馆和海豚馆'],
        ['mccid' => '7032', 'mcc_name' => '运动和娱乐露营地'],
        ['mccid' => '7033', 'mcc_name' => '活动房车场及露营场所'],
        ['mccid' => '5944', 'mcc_name' => '银器店'],
        ['mccid' => '5932', 'mcc_name' => '古玩店（出售、维修及还原）'],
        ['mccid' => '7631', 'mcc_name' => '手表、钟表和首饰维修店'],
        ['mccid' => '7999', 'mcc_name' => '未列入其他代码的娱乐服务'],
        ['mccid' => '1520', 'mcc_name' => '一般承包商－住宅与商业楼'],
        ['mccid' => '7013', 'mcc_name' => '不动产代理——房地产经纪'],
        ['mccid' => '5271', 'mcc_name' => '活动房车销售商'],
        ['mccid' => '5511', 'mcc_name' => '汽车货车经销商－主营新旧车的销售'],
        ['mccid' => '5521', 'mcc_name' => '汽车货车经销商－专门从事旧车的销售'],
        ['mccid' => '5551', 'mcc_name' => '船只销售商'],
        ['mccid' => '5561', 'mcc_name' => '旅行拖车、娱乐用车销售商'],
        ['mccid' => '5571', 'mcc_name' => '摩托车商店和经销商'],
        ['mccid' => '5592', 'mcc_name' => '露营、房车销售商'],
        ['mccid' => '5598', 'mcc_name' => '雪车商'],
        ['mccid' => '5599', 'mcc_name' => '汽车、飞行器、农用机车综合经营商'],
        ['mccid' => '5933', 'mcc_name' => '典当、拍卖、信托'],
        ['mccid' => '4011', 'mcc_name' => '铁路运输'],
        ['mccid' => '4119', 'mcc_name' => '救护车服务'],
        ['mccid' => '4215', 'mcc_name' => '快递服务（空运、地面运输或海运）'],
        ['mccid' => '4225', 'mcc_name' => '公共仓储服务－农产品、冷冻品和家用产品'],
        ['mccid' => '4411', 'mcc_name' => '轮船及巡游航线服务'],
        ['mccid' => '4457', 'mcc_name' => '出租船只'],
        ['mccid' => '4582', 'mcc_name' => '机场服务'],
        ['mccid' => '4789', 'mcc_name' => '未列入其他代码的运输服务'],
        ['mccid' => '4812', 'mcc_name' => '通讯设备和电话销售'],
        ['mccid' => '4816', 'mcc_name' => '计算机网络/信息服务'],
        ['mccid' => '5211', 'mcc_name' => '木材和各类建材卖场'],
        ['mccid' => '5231', 'mcc_name' => '玻璃、油漆涂料、墙纸零售'],
        ['mccid' => '5310', 'mcc_name' => '折扣商店'],
        ['mccid' => '5311', 'mcc_name' => '百货商店'],
        ['mccid' => '5399', 'mcc_name' => '其他综合零售'],
        ['mccid' => '5422', 'mcc_name' => '各类肉类零售商'],
        ['mccid' => '5441', 'mcc_name' => '糖果及坚果商店'],
        ['mccid' => '5451', 'mcc_name' => '乳制品店、冷饮店'],
        ['mccid' => '5462', 'mcc_name' => '面包房、糕点商店'],
        ['mccid' => '5532', 'mcc_name' => '汽车轮胎经销商'],
        ['mccid' => '5533', 'mcc_name' => '汽车零配件商店'],
        ['mccid' => '5611', 'mcc_name' => '男子和男童服装及用品商店'],
        ['mccid' => '5621', 'mcc_name' => '妇女成衣商店'],
        ['mccid' => '5631', 'mcc_name' => '女性用品商店'],
        ['mccid' => '5641', 'mcc_name' => '婴儿、儿童服装店'],
        ['mccid' => '5661', 'mcc_name' => '鞋店'],
        ['mccid' => '5681', 'mcc_name' => '皮货店'],
        ['mccid' => '5541', 'mcc_name' => '加油站、服务站'],
        ['mccid' => '5542', 'mcc_name' => '自助加油站'],
        ['mccid' => '5411', 'mcc_name' => '大型仓储式超级市场'],
        ['mccid' => '5722', 'mcc_name' => '大型家用电器商店'],
        ['mccid' => '4511', 'mcc_name' => '航空公司'],
        ['mccid' => '4111', 'mcc_name' => '本市和市郊通勤旅客运输（包括轮渡）'],
        ['mccid' => '4121', 'mcc_name' => '出租车服务'],
        ['mccid' => '4131', 'mcc_name' => '公路客运'],
        ['mccid' => '4784', 'mcc_name' => '路桥通行费'],
        ['mccid' => '3998', 'mcc_name' => '铁道部下属铁路局'],
        ['mccid' => '4112', 'mcc_name' => '铁路局指定的票务代售点'],
        ['mccid' => '4900', 'mcc_name' => '公共事业（电力、煤气、自来水、清洁服务）'],
        ['mccid' => '4814', 'mcc_name' => '电信服务'],
        ['mccid' => '4899', 'mcc_name' => '有线和其他付费电视服务'],
        ['mccid' => '6300', 'mcc_name' => '保险销售、保险业和保险金（POS 刷卡支付）'],
        ['mccid' => '5960', 'mcc_name' => '保险直销（批量代扣代付）'],
        ['mccid' => '8651', 'mcc_name' => '政治组织（政府机构)'],
        ['mccid' => '9211', 'mcc_name' => '法庭费用，包括赡养费和子女抚养费'],
        ['mccid' => '9222', 'mcc_name' => '罚款'],
        ['mccid' => '9223', 'mcc_name' => '保释金'],
        ['mccid' => '9311', 'mcc_name' => '纳税'],
        ['mccid' => '9399', 'mcc_name' => '未列入其他代码的政府服务'],
        ['mccid' => '9400', 'mcc_name' => '使领馆收费'],
        ['mccid' => '5994', 'mcc_name' => '报亭、报摊'],
        ['mccid' => '7523', 'mcc_name' => '停车场'],
        ['mccid' => '9402', 'mcc_name' => '国家邮政'],
        ['mccid' => '7011', 'mcc_name' => '住宿服务（旅馆、酒店、汽车旅馆、度假村等）'],
        ['mccid' => '5691', 'mcc_name' => '成人成衣店'],
        ['mccid' => '5698', 'mcc_name' => '假发商店'],
        ['mccid' => '5714', 'mcc_name' => '帏帐、窗帘、室内装潢商店'],
        ['mccid' => '5719', 'mcc_name' => '各种家庭装饰专营店'],
        ['mccid' => '5732', 'mcc_name' => '电子设备、家用电器商店'],
        ['mccid' => '5734', 'mcc_name' => '计算机软件商店'],
        ['mccid' => '5814', 'mcc_name' => '便民餐饮店，营业面积≦100 平方米'],
        ['mccid' => '5912', 'mcc_name' => '药房、药店'],
        ['mccid' => '5941', 'mcc_name' => '体育用品店'],
        ['mccid' => '5942', 'mcc_name' => '书店'],
        ['mccid' => '5943', 'mcc_name' => '文具用品商店、各类办公用品商店'],
        ['mccid' => '5946', 'mcc_name' => '照相器材商店'],
        ['mccid' => '5947', 'mcc_name' => '礼品、卡片、装饰品、纪念品商店'],
        ['mccid' => '5948', 'mcc_name' => '箱包、皮具店'],
        ['mccid' => '5972', 'mcc_name' => '邮票和纪念币商店'],
        ['mccid' => '5976', 'mcc_name' => '假肢店（整形外科用品、辅助设备）'],
        ['mccid' => '5977', 'mcc_name' => '化妆品商店'],
        ['mccid' => '5992', 'mcc_name' => '花店'],
        ['mccid' => '5993', 'mcc_name' => '香烟、雪茄专卖店'],
        ['mccid' => '6010', 'mcc_name' => '金融机构－人工现金支付'],
        ['mccid' => '6011', 'mcc_name' => '金融机构－自动现金支付'],
        ['mccid' => '6012', 'mcc_name' => '金融机构－商品和服务'],
        ['mccid' => '6051', 'mcc_name' => '非金融机构－外币兑换、非电子转账的汇票、临时支付凭证和旅行支票'],
        ['mccid' => '6211', 'mcc_name' => '证券公司－经纪人和经销商'],
        ['mccid' => '7217', 'mcc_name' => '室内清洁服务（地毯、沙发、家具表面的清洁服务）'],
        ['mccid' => '7221', 'mcc_name' => '摄影工作室'],
        ['mccid' => '7230', 'mcc_name' => '理发店'],
        ['mccid' => '7261', 'mcc_name' => '殡葬服务'],
        ['mccid' => '7273', 'mcc_name' => '婚姻介绍及陪同服务'],
        ['mccid' => '7277', 'mcc_name' => '咨询服务－债务、婚姻和私人事务'],
        ['mccid' => '7295', 'mcc_name' => '家政服务'],
        ['mccid' => '7296', 'mcc_name' => '出租衣物－服装、制服和正式场合服装'],
        ['mccid' => '7299', 'mcc_name' => '未列入其他代码的其他个人服务'],
        ['mccid' => '7311', 'mcc_name' => '广告服务'],
        ['mccid' => '7321', 'mcc_name' => '消费者信用报告机构'],
        ['mccid' => '7333', 'mcc_name' => '商业摄影、工艺、绘图服务'],
        ['mccid' => '7339', 'mcc_name' => '速记、秘书服务（包括各类办公服务）'],
        ['mccid' => '7349', 'mcc_name' => '清洁、保养及门卫服务'],
        ['mccid' => '7372', 'mcc_name' => '计算机编程、数据处理和系统集成设计服务'],
        ['mccid' => '7392', 'mcc_name' => '管理、咨询和公共关系服务'],
        ['mccid' => '7394', 'mcc_name' => '设备、工具、家具和电器出租'],
        ['mccid' => '7399', 'mcc_name' => '未列入其他代码的商业服务'],
        ['mccid' => '7512', 'mcc_name' => '汽车出租'],
        ['mccid' => '7513', 'mcc_name' => '卡车及拖车出租'],
        ['mccid' => '7519', 'mcc_name' => '房车和娱乐车辆出租'],
        ['mccid' => '7538', 'mcc_name' => '汽车服务商店（非经销商）'],
        ['mccid' => '7542', 'mcc_name' => '洗车'],
        ['mccid' => '7549', 'mcc_name' => '拖车服务'],
        ['mccid' => '7622', 'mcc_name' => '电器设备维修'],
        ['mccid' => '7623', 'mcc_name' => '空调、制冷设备维修'],
        ['mccid' => '7629', 'mcc_name' => '电器设备、小家电维修'],
        ['mccid' => '7641', 'mcc_name' => '家具维修、翻新'],
        ['mccid' => '7692', 'mcc_name' => '焊接维修服务'],
        ['mccid' => '7699', 'mcc_name' => '各类维修店及相关服务'],
        ['mccid' => '7832', 'mcc_name' => '电影院'],
        ['mccid' => '7841', 'mcc_name' => '音像制品出租商店'],
        ['mccid' => '7991', 'mcc_name' => '旅游与展览'],
        ['mccid' => '7995', 'mcc_name' => '彩票销售'],
        ['mccid' => '8011', 'mcc_name' => '其他医疗卫生活动'],
        ['mccid' => '8021', 'mcc_name' => '牙科医生'],
        ['mccid' => '8031', 'mcc_name' => '正骨医生'],
        ['mccid' => '8041', 'mcc_name' => '按摩医生'],
        ['mccid' => '8042', 'mcc_name' => '眼科医生'],
        ['mccid' => '8043', 'mcc_name' => '光学产品、眼镜店'],
        ['mccid' => '8050', 'mcc_name' => '护理和照料服务'],
        ['mccid' => '8071', 'mcc_name' => '医学及牙科实验室'],
        ['mccid' => '8099', 'mcc_name' => '其他医疗保健服务'],
        ['mccid' => '8111', 'mcc_name' => '法律服务和律师事务所服务'],
        ['mccid' => '8241', 'mcc_name' => '函授学校（成人教育）'],
        ['mccid' => '8299', 'mcc_name' => '其他学校和教育服务'],
        ['mccid' => '8351', 'mcc_name' => '儿童保育服务（含学前教育）'],
        ['mccid' => '8675', 'mcc_name' => '汽车协会'],
        ['mccid' => '8699', 'mcc_name' => '其他会员组织'],
        ['mccid' => '8911', 'mcc_name' => '建筑、工程和测量服务'],
        ['mccid' => '8912', 'mcc_name' => '装修、装潢、园艺'],
        ['mccid' => '8931', 'mcc_name' => '会计、审计、财务服务'],
        ['mccid' => '8999', 'mcc_name' => '未列入其他代码的专业服务'],
        ['mccid' => '742', 'mcc_name' => '兽医服务'],
        ['mccid' => '763', 'mcc_name' => '农业合作'],
        ['mccid' => '780', 'mcc_name' => '景观美化及园艺服务'],
        ['mccid' => '4214', 'mcc_name' => '货物搬运和托运—当地和长途，移动和存储公司，以及当地递送服务'],
        ['mccid' => '4468', 'mcc_name' => '船舶、海运服务提供商'],
        ['mccid' => '4821', 'mcc_name' => '电报服务'],
        ['mccid' => '5251', 'mcc_name' => '五金商店'],
        ['mccid' => '5261', 'mcc_name' => '草坪、花园用品商店'],
        ['mccid' => '5309', 'mcc_name' => '免税商店'],
        ['mccid' => '5331', 'mcc_name' => '各类杂货店、便利店'],
        ['mccid' => '5499', 'mcc_name' => '各类食品店及专门食品零售店'],
        ['mccid' => '5651', 'mcc_name' => '家庭服装商店'],
        ['mccid' => '5655', 'mcc_name' => '运动服饰商店'],
        ['mccid' => '5697', 'mcc_name' => '裁缝、修补、改衣店'],
        ['mccid' => '5699', 'mcc_name' => '各类服装及饰物店'],
        ['mccid' => '5712', 'mcc_name' => '家具、家庭摆品、家用设备零售商'],
        ['mccid' => '5713', 'mcc_name' => '地板商店'],
        ['mccid' => '5718', 'mcc_name' => '壁炉、壁炉防护网及配件商店'],
        ['mccid' => '5733', 'mcc_name' => '音乐商店－乐器、钢琴、乐谱'],
        ['mccid' => '5735', 'mcc_name' => '音像制品商店'],
        ['mccid' => '5921', 'mcc_name' => '瓶装酒零售店'],
        ['mccid' => '5931', 'mcc_name' => '旧商品店、二手商品店'],
        ['mccid' => '5935', 'mcc_name' => '海上船只遇难救助'],
        ['mccid' => '5940', 'mcc_name' => '自行车商店'],
        ['mccid' => '5945', 'mcc_name' => '玩具、游戏店'],
        ['mccid' => '5949', 'mcc_name' => '纺织品及针织品零售'],
        ['mccid' => '5962', 'mcc_name' => '旅游相关服务直销'],
        ['mccid' => '5963', 'mcc_name' => '门对门销售'],
        ['mccid' => '5964', 'mcc_name' => '目录直销商户'],
        ['mccid' => '5965', 'mcc_name' => '目录、零售兼营商户'],
        ['mccid' => '5966', 'mcc_name' => '电话呼出直销'],
        ['mccid' => '5967', 'mcc_name' => '电话呼入直销'],
        ['mccid' => '5968', 'mcc_name' => '订阅/订购直销服务'],
        ['mccid' => '5969', 'mcc_name' => '其他直销商户'],
        ['mccid' => '5973', 'mcc_name' => '宗教品商店'],
        ['mccid' => '5975', 'mcc_name' => '助听器－销售、服务和用品'],
        ['mccid' => '9498', 'mcc_name' => '信用卡还款'],
    ];

    /**
     * 结算id对应商户特征
    */
    public const SETTLER_ID_TO_MCH_FEATURE = [
        ['subject_type' => '企业', 'settle_id' => '756', 'apply_industry' => '适用于游戏、网络虚拟（在线图书/视频/音乐、游戏、网络直播、门户论坛、网络广告及推广、软件开发）、电商团购、财经资讯/荐股、众筹、电信运营商/宽带收费、机票/机票代理、共享服务、网购平台、在线信息服务平台、O2O 平台、信用还款'],
        ['subject_type' => '政府事业单位', 'settle_id' => '773', 'apply_industry' => '适用于游戏、网络虚拟（在线图书/视频/音乐、游戏、网络直播、门户论坛、网络广告及推广、软件开发）、电商团购、财经资讯/荐股、众筹、电信运营商/宽带收费、机票/机票代理、共享服务、网购平台、在线信息服务平台、O2O 平台、信用还款'],
        ['subject_type' => '其他组织', 'settle_id' => '774', 'apply_industry' => '适用于游戏、网络虚拟（在线图书/视频/音乐、游戏、网络直播、门户论坛、网络广告及推广、软件开发）、电商团购、财经资讯/荐股、众筹、电信运营商/宽带收费、机票/机票代理、共享服务、网购平台、在线信息服务平台、O2O 平台、信用还款'],
        ['subject_type' => '小微商户', 'settle_id' => '775', 'apply_industry' => '适用于游戏、网络虚拟（在线图书/视频/音乐、游戏、网络直播、门户论坛、网络广告及推广、软件开发）、电商团购、财经资讯/荐股、众筹、电信运营商/宽带收费、机票/机票代理、共享服务、网购平台、在线信息服务平台、O2O 平台、信用还款'],
        ['subject_type' => '企业', 'settle_id' => '757', 'apply_industry' => '适用于保险公司、保险代理公司'],
        ['subject_type' => '企业', 'settle_id' => '758', 'apply_industry' => '适用于餐饮、零售批发、交通出行、生活娱乐服务、民营医疗机构、缴费、加油、物流快递等业务'],
        ['subject_type' => '企业', 'settle_id' => '759', 'apply_industry' => '民办中小学、幼儿园业务'],
        ['subject_type' => '企业', 'settle_id' => '760', 'apply_industry' => '适用于水电煤暖气民生缴费、交通罚款、公交/高速'],
        ['subject_type' => '个体户', 'settle_id' => '761', 'apply_industry' => '适用于电商团购、电信运营商/宽带收费、机票/机票代理'],
        ['subject_type' => '个体户', 'settle_id' => '762', 'apply_industry' => '适用于餐饮、零售批发、交通出行、生活娱乐服务、民营医疗机构、缴费等业务'],
        ['subject_type' => '政府事业单位', 'settle_id' => '763', 'apply_industry' => '适用于停车缴费、物业缴费等其他缴费类业务'],
        ['subject_type' => '政府事业单位', 'settle_id' => '764', 'apply_industry' => '适用于水电煤暖气民生缴费、交通罚款、公交/高速'],
        ['subject_type' => '政府事业单位', 'settle_id' => '765', 'apply_industry' => '适用于公立医院、公立院校及指定要求的挂号平台、民办大学院校及公益基金会、党费、政府非税业务'],
        ['subject_type' => '其他组织', 'settle_id' => '766', 'apply_industry' => '适用于餐饮、零售批发、交通出行、生活娱乐服务、民营医疗机构、缴费、物流快递等业务'],
        ['subject_type' => '其他组织', 'settle_id' => '767', 'apply_industry' => '民办中小学、幼儿园业务'],
        ['subject_type' => '其他组织', 'settle_id' => '768', 'apply_industry' => '适用于水电煤暖气民生缴费、交通罚款、公交/高速'],
        ['subject_type' => '其他组织', 'settle_id' => '769', 'apply_industry' => '适用于民办大学院校及公益基金会'],
        ['subject_type' => '小微商户', 'settle_id' => '770', 'apply_industry' => '适用于餐饮、零售批发、交通出行、生活娱乐服务、缴费、加油、物流快递等业务'],
        ['subject_type' => '企业', 'settle_id' => '771', 'apply_industry' => '适用于电商及游戏行业'],
    ];

    /**
     * 产品类型
    */
    public const product_type = [
        ['product_type' => '208X4XXW', 'product_name' => '网上收银微信支付', 'product_desc' => '费率不低于百分之 0.23'],
        ['product_type' => '208X4XXA', 'product_name' => '网上收银支付宝支付', 'product_desc' => '费率不低于百分之 0.23'],
        ['product_type' => '208X4X1U', 'product_name' => '网上收银云闪付支付-借', 'product_desc' => ''],
        ['product_type' => '208X4X2U', 'product_name' => '网上收银云闪付支付-贷', 'product_desc' => '填写credit_rate贷记卡费率'],
        ['product_type' => '208X4L1X', 'product_name' => '网上收银H5网关支付-借', 'product_desc' => ''],
        ['product_type' => '208X4L2X', 'product_name' => '网上收银H5网关支付-贷', 'product_desc' => '填写credit_rate贷记卡费率'],
        ['product_type' => '208X0X1X', 'product_name' => '网上收银协议支付-借', 'product_desc' => ''],
        ['product_type' => '208X0X2X', 'product_name' => '网上收银协议支付-贷', 'product_desc' => '填写credit_rate贷记卡费率'],
        ['product_type' => '208X48XX', 'product_name' => '网上收银B2B支付', 'product_desc' => '费率单位：元/笔'],
        ['product_type' => '208X491X', 'product_name' => '网上收银B2C支付-借', 'product_desc' => ''],
        ['product_type' => '208X492X', 'product_name' => '网上收银B2C支付-贷', 'product_desc' => '填写credit_rate贷记卡费率'],
        ['product_type' => '208X5OXW', 'product_name' => 'pos终端微信支付', 'product_desc' => ''],
        ['product_type' => '208X5OXA', 'product_name' => 'pos终端支付宝支付  ', 'product_desc' => ''],
        ['product_type' => '208X5O1U', 'product_name' => 'pos终端云闪付支付-借', 'product_desc' => ''],
        ['product_type' => '208X5O2U', 'product_name' => 'pos终端云闪付支付-贷', 'product_desc' => '填写credit_rate贷记卡费率'],
        ['product_type' => '208X5N1X', 'product_name' => 'pos终端刷卡支付-借', 'product_desc' => '填写rate费率，同时必须填写max_amt封顶'],
        ['product_type' => '208X5N2X', 'product_name' => 'pos终端刷卡支付-贷', 'product_desc' => '填写credit_rate贷记卡费率'],
        ['product_type' => '208X5N9X', 'product_name' => 'pos终端外卡支付', 'product_desc' => ''],
        ['product_type' => '208X5PXW', 'product_name' => '微信码牌支付', 'product_desc' => ''],
        ['product_type' => '208X5PXA', 'product_name' => '支付宝码牌支付', 'product_desc' => ''],
        ['product_type' => '208X5P1U', 'product_name' => '云闪付码牌支付-借', 'product_desc' => ''],
        ['product_type' => '208X5P2U', 'product_name' => '云闪付码牌支付-贷', 'product_desc' => '填写credit_rate贷记卡费率'],
    ];
}